# Generated by Django 5.1.7 on 2025-04-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_surveillancecalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='state_abbreviation',
            field=models.CharField(blank=True, help_text='State/Territory abbreviation (e.g., NT, QLD, WA)', max_length=3, null=True),
        ),
    ]
