# Generated by Django 5.1.7 on 2025-04-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_region_state_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='formatted_address',
            field=models.CharField(blank=True, help_text='Full address string selected via Geoscape API', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='geoscape_address_id',
            field=models.CharField(blank=True, help_text='Unique identifier from Geoscape API for the selected address', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='has_exact_address',
            field=models.BooleanField(default=False, help_text='Indicates if the user provided an exact address via search'),
        ),
    ]
