# Generated by Django 5.1.7 on 2025-04-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_farm_formatted_address_farm_geoscape_address_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='boundary',
            field=models.JSONField(blank=True, help_text='Cadastral boundary polygon data (e.g., GeoJSON) from Geoscape API', null=True),
        ),
    ]
