# Generated by Django 5.1.7 on 2025-04-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_boundarymappingtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('affects_plant_parts', models.ManyToManyField(blank=True, related_name='diseases', to='core.plantpart')),
                ('affects_plant_types', models.ManyToManyField(blank=True, related_name='diseases', to='core.planttype')),
            ],
        ),
        migrations.AddField(
            model_name='surveillancerecord',
            name='diseases_found',
            field=models.ManyToManyField(blank=True, related_name='surveillance_records', to='core.disease'),
        ),
    ]
