# Generated by Django 5.1.7 on 2025-05-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_disease_surveillancerecord_diseases_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for the stage (e.g., 'Flowering', 'Early Fruit Development')", max_length=100, unique=True)),
                ('months', models.CharField(help_text='Comma-separated list of month numbers (1-12) this stage applies to. Handles year rollover.', max_length=50)),
                ('prevalence_p', models.DecimalField(decimal_places=3, help_text='Estimated pest/disease prevalence (e.g., 0.05 for 5%) during this stage, used in calculations.', max_digits=4)),
                ('active_diseases', models.ManyToManyField(blank=True, help_text='Diseases that are typically active during this stage.', related_name='seasonal_stages', to='core.disease')),
                ('active_pests', models.ManyToManyField(blank=True, help_text='Pests that are typically active during this stage.', related_name='seasonal_stages', to='core.pest')),
                ('recommended_parts', models.ManyToManyField(blank=True, help_text='Plant parts recommended for inspection during this stage.', related_name='seasonal_stages', to='core.plantpart')),
            ],
            options={
                'verbose_name': 'Seasonal Stage Mapping',
                'verbose_name_plural': 'Seasonal Stage Mappings',
                'ordering': ['id'],
            },
        ),
    ]
