# Generated by Django 5.1.7 on 2025-05-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_populate_seasonal_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonalstage',
            name='recommended_parts',
        ),
    ]
