# Generated by Django 4.2.20 on 2025-05-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_observation_surveysession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20),
        ),
    ]
